### PR TITLE
feat: Add index for helm dependencies

### PR DESCRIPTION
**Pull request by yurifrl**
Hi, If we added a index.yaml on the root folder we could use this repo as a helm repository and use it a helm dependency like so:

```
# Chart.yaml
dependencies:
- name: prow
  version: "v0.9.0"
  repository: https://raw.githubusercontent.com/dafiti-group/prow-helm-chart/master/
```
If you guys point me to the general direction and can make this index.yaml be generated with the release build

### CODE REVIEW

**Comment by givanov** [comment]
@yurifrl we'll look into this in the near future and have proper chart releases. In the meantime I'll close this PR.

**Comment by yurifrl** [comment]
Ok @givanov please let me know if I can help, I'd love to.

**Comment by givanov** [comment]
@yurifrl as of #95 we're now pushing the chart to our helm repo https://charts.ouzi.io . Let me know if you have any issues using that.

**Comment by yurifrl** [comment]
@givanov I tested here, and it works great.

**Pull request closed without merging**
